spring:
  datasource:
  url: jdbc:mysql://43.203.207.173:3306/awsUser?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  username: tpdms
  password: mysql

  driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
